apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runai-cluster-ingress
  namespace: runai
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"

    nginx.ingress.kubernetes.io/websocket-services: "runai-cluster-ingress"
spec:
  ingressClassName: nginx

  tls:
  - hosts:
    - placeholder.runai.langgoose.com
    secretName: runai-tls-placeholder

  rules:
  - host: placeholder.runai.langgoose.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: runai-cluster-ingress
            port:
              number: 443
