apiVersion: v1
kind: Pod
metadata:
  name: image-pull-test
  namespace: nim7
spec:
  containers:
  - name: test-container
    image: nvcr.io/nim/mistralai/mistral-7b-instruct-v0.3:1.3.0
    command: ["sleep", "3600"]  # Keeps the pod running
  imagePullSecrets:
  - name: nim7-ngc-secret
  restartPolicy: Never
