##Rafay Project name
projectName: UPDATE_EXISTING_PROJECT_NAME
## Initial Version for Environment Manager resources.
version: v1
## https://docs.rafay.dev/env_manager/overview/
##Environment Manager resourceTemplate Name
## https://docs.rafay.dev/env_manager/templates/resource_templates/
IRSAResourceTemplate: 101-genai-eks-aws-irsa
GenAIResourceTemplate: 101-genai-eks-aws-genai
## Environment Manager environmentTemplate Name
## https://docs.rafay.dev/env_manager/templates/environment_templates/
AIEnvironmentTemplate: eks-ai-apps
## Terraform code path 
tfRepoPathIRSA: terraform/aws/101-genai-eks/terraform/irsa
tfRepoPathGenAI: terraform/aws/101-genai-eks/terraform/genai
awsRegion: us-east-1
EKSClusterName: ai-eks-cluster
